### ISSUE TITLE
singleLanguage doesn't work in user blueprint

### ISSUE THREAD

**Issue by BenediktEngel** [mullema/k3-panel-view-extended#14]
Hey,
I am using Kirby 3.5.7.1 and version 3.0 from this plugin (like described in the readme). I want to hide the languageswitcher also in the user blueprint. But this doesn't work. In page blueprints everything works fine and as expected. 
Maybe you can help me or fix this issue.
Thanks a lot.

**Comment by mullema** [comment]
Hi @BenediktEngel 
What does your blueprint look like? 

This plugin does hide the language selector in the content section, not the selector for the panel language.

**Comment by BenediktEngel** [comment]
Yes, I know. For the panel language an option already exists in vanilla kirby. 
Thats the blueprint I try to use:
```yaml
title: User
options:
  singleLanguage: true
permissions:
  access:
    panel: true
    site: true
    settings: false
    users: false
  user:
    changeRole: false
    delete: false
    update: false 
    changeEmail: false
    changeName: false
    changeLanguage: false
fields:
   #...
```
