### ISSUE TITLE
bug/feat: after ChangeTemplate from/to a multilanguage- to singlelanguage-blueprint the language-switcher does not appear/disapper

### ISSUE THREAD

**Issue by dennisbaum** [mullema/k3-panel-view-extended#17]
K3.6.3
plugin-version: 4.0.0

I have a set of pages, with multilanguage- and singlelanguage-blueprints.

message.yml
```yaml
options:
  changeTemplate:
    - message
    - message-en
```

message-en.yml
```yaml
options:
  singleLanguage: true
  changeTemplate:
    - message
    - message-en
```

if i enable the option `changeTemplate` and the editor change from/to single- or multilanguage, the language switcher will not be updated. if i reload the panel-page, it is.
is there some kind of changeTemplate hook, where you can update the language-switcher,
or at least reload the page?

thx!
