### ISSUE TITLE
[Bug] Settings Menu Still Visible in Pages List Despite `hideSettings: true`

### ISSUE THREAD

**Issue by luxlogica** [mullema/k3-panel-view-extended#2]
Not sure whether this should be classified as a 'bug', or as a 'feature request'.

When we set `hideSettings: true` in a blueprint, it _does_ hide the main settings menu from the page in the Panel. However, if that page is listed in a Pages Field somewhere else in the site, the settings menu for the page (within the list row) is still visible.

<img width="457" alt="screen shot 2019-01-25 at 6 35 33 pm" src="https://user-images.githubusercontent.com/2994472/51731791-2d7d8d00-20d0-11e9-96f7-5b3305d39c07.png">

It would be nice if there were a way to also hide _this_ menu on `hideSetttings: true`.

**Comment by mullema** [comment]
True, I haven't thought about that. I wanted to hide the  settings menu only. 
There's a css solution that hides all options in a pages section though.

```css
/* remove options in pages list by Section */
section.k-section-name-yoursectionname div.k-list-item-options {
    display: none;
}
```
or

```css
/* remove options in all pages lists on this page (level_0) */
.k-page-view.yourpage.level_0 div.k-list-item-options {
    display: none;
}
```
